### ISSUE TITLE
How to use this ?

### ISSUE THREAD

**Issue by lalishansh** [charmoniumQ/antlr4-python-grun#1]
How can we use pygrun ??
how do i run `grun hello.g4 r -tree`, if that's even possible ?
what are the features it's missing etc.

**Comment by charmoniumQ** [comment]
I've updated the [README](https://github.com/charmoniumQ/antlr4-python-grun/blob/main/README.rst) with usage notes. Does this answer your question? 

Basically, `pygrun parse --format s-expr grammar.g4 input_file_to_parse`

**Comment by lalishansh** [comment]
Sure Thanks 👌
